export const MEDICOS = [
  { id: "dr_andre_ventura", nome: "Dr. André Ventura da Nóbrega" },
  { id: "dr_arquimedes_aires", nome: "Dr. Arquimedes Aires Braga de Lira" },
  { id: "dr_arthur_jose", nome: "Dr. Arthur José Ventura da Nóbrega" },
  { id: "dr_diego_furtado", nome: "Dr. Diego Furtado F. Cândido" },
  { id: "dr_diogo_araujo", nome: "Dr. Diogo Araújo" },
  { id: "dr_ednaldo_marques", nome: "Dr. Ednaldo Marques Bezerra Filho" },
  { id: "dr_felix_soares", nome: "Dr. Félix Soares Nóbrega" },
  { id: "dr_filipe_anderson", nome: "Dr. Filipe Anderson de Souza Florentino" },
  { id: "dr_heraclio_almeida", nome: "Dr. Heráclio Almeida da Costa" },
  { id: "dr_heverton_leal", nome: "Dr. Heverton Leal Ernesto de Amorim" },
  { id: "dr_igor_silveira", nome: "Dr. Igor Silveira de Castro Guerreiro Gondim" },
  { id: "dr_jannie_Miranda", nome: "Dr. Janniê de Miranda Araújo" },
  { id: "dr_jose_celio", nome: "Dr. José Célio Couto" },
  { id: "dr_jose_roberto", nome: "Dr. José Roberto Maia Júnior" },
  { id: "dr_mario_henrique", nome: "Dr. Mario Henrique de Melo Carneiro" },
  { id: "dr_pericles_almeida", nome: "Dr. Péricles Almeida da Costa" },
  { id: "dr_rafael_borges", nome: "Dr. Rafael Borges Tavares Cavalcanti" },
  { id: "dr_raiff_ramalho", nome: "Dr. Raiff Ramalho Cavalcanti" },
  { id: "dr_ramonie_miranda", nome: "Dr. Ramoniê de Miranda Araújo" },
  { id: "dr_rennah_goncalves", nome: "Dr. Rennah Gonçalves dos Santos" },
  { id: "dr_rodolfo_nunes", nome: "Dr. Rodolfo Nunes" },
  { id: "dr_saulo_nobrega", nome: "Dr. Saulo Nóbrega" },
  { id: "dr_ygor_felipe", nome: "Dr. Ygor W. Felipe Barbosa" },
  { id: "dra_adriana_susanne", nome: "Dra. Adriana Susanne Jalcira Jeunon" },
  { id: "dra_cinthia_milena", nome: "Dra. Cinthia Milena Veiga de Oliveira Marques" },
  { id: "dra_fernanda_borges", nome: "Dra. Fernanda Borges Tavares Cavalcanti" },
  { id: "dra_larissa_mendonca", nome: "Dra. Larissa Mendonça de Souza" },
  { id: "dra_larissa_nobrega", nome: "Dra. Larissa Nóbrega Leal de Amorim" },
  { id: "dra_mariana_lellis", nome: "Dra. Mariana Lellis de Macedo" },
  { id: "dra_miriam_maria", nome: "Dra. Míriam Maria Barbosa Albino" },
  { id: "dra_priscila_borba", nome: "Dra. Priscila Borba" },
  { id: "dra_rafaella_tiburtino", nome: "Dra. Rafaella Tiburtino" },
];
